// merchant/products/-server/products.mock.ts

import type { MerchantProductsData } from '../products.types'

export const mockMerchantProducts: MerchantProductsData = {
  stats: {
    total: 24,
    active: 18,
    outOfStock: 3,
    inventoryValue: 1_240_000,
  },
  products: [
    {
      id: 'PRD-001',
      name: 'حذاء رياضي أبيض',
      sku: 'SKU-001-WHT',
      category: 'أحذية',
      thumbnail: '👟',
      stockQuantity: 47,
      lowStockThreshold: 10,
      basePrice: 2400,
      msrpPrice: 3200,
      minSellingPrice: 2800,
      status: 'active',
      isActive: true,
      mediaFolderUrl: 'https://drive.google.com/drive/folders/example1',
      description: 'حذاء رياضي خفيف مناسب للجري اليومي',
      createdAt: '2025-06-01',
    },
    {
      id: 'PRD-002',
      name: 'سترة شتوية كحلي',
      sku: 'SKU-002-NVY',
      category: 'ملابس',
      thumbnail: '🧥',
      stockQuantity: 7,
      lowStockThreshold: 10,
      basePrice: 4000,
      msrpPrice: 5500,
      minSellingPrice: 4800,
      status: 'active',
      isActive: true,
      mediaFolderUrl: 'https://drive.google.com/drive/folders/example2',
      description: 'سترة شتوية دافئة بجودة عالية',
      createdAt: '2025-06-05',
    },
    {
      id: 'PRD-003',
      name: 'حقيبة جلدية بنية',
      sku: 'SKU-003-BRN',
      category: 'حقائب',
      thumbnail: '👜',
      stockQuantity: 0,
      lowStockThreshold: 5,
      basePrice: 3500,
      msrpPrice: 4800,
      minSellingPrice: 4200,
      status: 'out_of_stock',
      isActive: false,
      description: 'حقيبة جلد طبيعي للاستخدام اليومي',
      createdAt: '2025-06-10',
    },
    {
      id: 'PRD-004',
      name: 'حذاء كلاسيكي أسود',
      sku: 'SKU-004-BLK',
      category: 'أحذية',
      thumbnail: '👞',
      stockQuantity: 23,
      lowStockThreshold: 10,
      basePrice: 3200,
      msrpPrice: 4500,
      minSellingPrice: 3800,
      status: 'paused',
      isActive: false,
      mediaFolderUrl: 'https://drive.google.com/drive/folders/example4',
      description: 'حذاء رسمي أنيق للمناسبات',
      createdAt: '2025-06-15',
    },
    {
      id: 'PRD-005',
      name: 'شنطة ظهر رياضية',
      sku: 'SKU-005-BLU',
      category: 'حقائب',
      thumbnail: '🎒',
      stockQuantity: 15,
      lowStockThreshold: 8,
      basePrice: 2800,
      msrpPrice: 3900,
      minSellingPrice: 3400,
      status: 'active',
      isActive: true,
      createdAt: '2025-06-20',
    },
  ],
}