import type { AffiliateDashboardData } from '../dashboard.types'

export const mockDashboardData: AffiliateDashboardData = {
  stats: {
    totalEarnings: 184500,
    availableBalance: 97200,
    deliveredRate: 74,
    retourRate: 18,
  },
  topMerchants: [
    {
      id: 'm1',
      name: 'تيك ستور الجزائر',
      category: 'إلكترونيات',
      deliveredRate: 82,
      retourRate: 11,
      totalOrders: 143,
      earnings: 58400,
    },
    {
      id: 'm2',
      name: 'موضة 24',
      category: 'ملابس',
      deliveredRate: 76,
      retourRate: 16,
      totalOrders: 98,
      earnings: 34100,
    },
    {
      id: 'm3',
      name: 'بيوتي برو',
      category: 'تجميل',
      deliveredRate: 79,
      retourRate: 13,
      totalOrders: 87,
      earnings: 29800,
    },
    {
      id: 'm4',
      name: 'سبور لاند',
      category: 'رياضة',
      deliveredRate: 68,
      retourRate: 24,
      totalOrders: 61,
      earnings: 22200,
    },
    {
      id: 'm5',
      name: 'كيدز ورلد',
      category: 'أطفال',
      deliveredRate: 71,
      retourRate: 21,
      totalOrders: 54,
      earnings: 18700,
    },
  ],
  recentOrders: [
    {
      id: 'o1',
      orderId: 'ORD-9841',
      productName: 'سماعات بلوتوث XG500',
      merchantName: 'تيك ستور الجزائر',
      status: 'delivered',
      commission: 850,
      updatedAt: 'منذ 12 دقيقة',
    },
    {
      id: 'o2',
      orderId: 'ORD-9840',
      productName: 'كريم مرطب فيتامين C',
      merchantName: 'بيوتي برو',
      status: 'shipped',
      commission: 420,
      updatedAt: 'منذ 34 دقيقة',
    },
    {
      id: 'o3',
      orderId: 'ORD-9835',
      productName: 'جاكيت رياضي أديداس',
      merchantName: 'سبور لاند',
      status: 'returned',
      commission: 0,
      updatedAt: 'منذ ساعة',
    },
    {
      id: 'o4',
      orderId: 'ORD-9829',
      productName: 'حذاء كاجوال جلد',
      merchantName: 'موضة 24',
      status: 'confirmed',
      commission: 620,
      updatedAt: 'منذ 2 ساعة',
    },
    {
      id: 'o5',
      orderId: 'ORD-9821',
      productName: 'لعبة تعليمية STEM',
      merchantName: 'كيدز ورلد',
      status: 'delivered',
      commission: 380,
      updatedAt: 'منذ 3 ساعات',
    },
  ],
}