import type { CampaignsData } from '../campaigns.types'

export const mockCampaignsData: CampaignsData = {

  stats: {
    totalCampaigns:     { value: 47, change: 14  },
    activeCampaigns:    { value: 31, change: 9   },
    pendingApproval:    { value: 9,  change: 3   },
    suspendedCampaigns: { value: 7,  change: -2  },
  },

  campaigns: [
    {
      id: 'cam_01',
      productName:    'قلادة قلب ذهبية',
      merchantName:   'Bijoux DZ',
      merchantWilaya: 'Alger',
      commissionRate: 8,
      status:         'active',
      conversions:    278,
      totalSales:     2800000,
      returnRate:     12,
      affiliatesCount: 14,
      createdAt:      '2024-10-01',
    },
    {
      id: 'cam_02',
      productName:    'عطر ليلى',
      merchantName:   'Parfums Pro',
      merchantWilaya: 'Oran',
      commissionRate: 10,
      status:         'pending',
      conversions:    0,
      totalSales:     0,
      returnRate:     0,
      affiliatesCount: 0,
      createdAt:      '2025-01-15',
    },
    {
      id: 'cam_03',
      productName:    'مكمل غذائي X',
      merchantName:   'HealthStore',
      merchantWilaya: 'Constantine',
      commissionRate: 15,
      status:         'suspended',
      conversions:    91,
      totalSales:     450000,
      returnRate:     76,
      affiliatesCount: 6,
      createdAt:      '2024-08-20',
      suspendedAt:    '2025-01-10',
      suspendedBy:    'Abdelouakil',
      suspendReason:  'نسبة إرجاع مرتفعة جداً (76%)',
    },
    {
      id: 'cam_04',
      productName:    'سماعات بلوتوث Pro',
      merchantName:   'TechShop DZ',
      merchantWilaya: 'Sétif',
      commissionRate: 7,
      status:         'active',
      conversions:    193,
      totalSales:     1950000,
      returnRate:     8,
      affiliatesCount: 11,
      createdAt:      '2024-11-05',
    },
    {
      id: 'cam_05',
      productName:    'كريم العناية بالبشرة',
      merchantName:   'Beauty Algeria',
      merchantWilaya: 'Annaba',
      commissionRate: 12,
      status:         'active',
      conversions:    341,
      totalSales:     3100000,
      returnRate:     21,
      affiliatesCount: 19,
      createdAt:      '2024-09-12',
    },
    {
      id: 'cam_06',
      productName:    'حقيبة جلدية فاخرة',
      merchantName:   'Leather Craft',
      merchantWilaya: 'Tlemcen',
      commissionRate: 9,
      status:         'pending',
      conversions:    0,
      totalSales:     0,
      returnRate:     0,
      affiliatesCount: 0,
      createdAt:      '2025-01-18',
    },
    {
      id: 'cam_07',
      productName:    'حذاء رياضي نسائي',
      merchantName:   'SportWear DZ',
      merchantWilaya: 'Blida',
      commissionRate: 6,
      status:         'active',
      conversions:    156,
      totalSales:     1200000,
      returnRate:     31,
      affiliatesCount: 9,
      createdAt:      '2024-12-01',
    },
    {
      id: 'cam_08',
      productName:    'مكيف هواء محمول',
      merchantName:   'ElectroStore',
      merchantWilaya: 'Batna',
      commissionRate: 5,
      status:         'banned',
      conversions:    44,
      totalSales:     320000,
      returnRate:     88,
      affiliatesCount: 3,
      createdAt:      '2024-07-10',
      suspendedAt:    '2024-09-01',
      suspendedBy:    'Abdelouakil',
      suspendReason:  'منتج مزيف — تم التحقق',
    },
    {
      id: 'cam_09',
      productName:    'ساعة ذكية للأطفال',
      merchantName:   'KidsWorld',
      merchantWilaya: 'Oran',
      commissionRate: 11,
      status:         'active',
      conversions:    87,
      totalSales:     870000,
      returnRate:     5,
      affiliatesCount: 7,
      createdAt:      '2024-12-20',
    },
    {
      id: 'cam_10',
      productName:    'عصير طبيعي بارد',
      merchantName:   'Fresh Algeria',
      merchantWilaya: 'Alger',
      commissionRate: 13,
      status:         'pending',
      conversions:    0,
      totalSales:     0,
      returnRate:     0,
      affiliatesCount: 0,
      createdAt:      '2025-01-20',
    },
  ],

  monthlyConversions: [
    { month: 'Jan', conversions: 210,  revenue: 1260000  },
    { month: 'Feb', conversions: 285,  revenue: 1710000  },
    { month: 'Mar', conversions: 340,  revenue: 2040000  },
    { month: 'Apr', conversions: 390,  revenue: 2340000  },
    { month: 'May', conversions: 445,  revenue: 2670000  },
    { month: 'Jun', conversions: 510,  revenue: 3060000  },
    { month: 'Jul', conversions: 480,  revenue: 2880000  },
    { month: 'Aug', conversions: 520,  revenue: 3120000  },
    { month: 'Sep', conversions: 590,  revenue: 3540000  },
    { month: 'Oct', conversions: 650,  revenue: 3900000  },
    { month: 'Nov', conversions: 710,  revenue: 4260000  },
    { month: 'Dec', conversions: 692,  revenue: 4152000  },
  ],

  topCampaigns: [
    { id: 'cam_05', productName: 'كريم العناية بالبشرة', merchantName: 'Beauty Algeria', conversions: 341, revenue: 3100000, commissionRate: 12 },
    { id: 'cam_01', productName: 'قلادة قلب ذهبية',      merchantName: 'Bijoux DZ',      conversions: 278, revenue: 2800000, commissionRate: 8  },
    { id: 'cam_04', productName: 'سماعات بلوتوث Pro',    merchantName: 'TechShop DZ',    conversions: 193, revenue: 1950000, commissionRate: 7  },
    { id: 'cam_07', productName: 'حذاء رياضي نسائي',    merchantName: 'SportWear DZ',   conversions: 156, revenue: 1200000, commissionRate: 6  },
    { id: 'cam_09', productName: 'ساعة ذكية للأطفال',   merchantName: 'KidsWorld',      conversions: 87,  revenue: 870000,  commissionRate: 11 },
  ],

  categoryStats: [
    { category: 'مجوهرات',      campaigns: 8,  conversions: 620 },
    { category: 'إلكترونيات',   campaigns: 11, conversions: 890 },
    { category: 'عناية وجمال',  campaigns: 9,  conversions: 740 },
    { category: 'أزياء',        campaigns: 7,  conversions: 510 },
    { category: 'غذاء وصحة',    campaigns: 6,  conversions: 340 },
    { category: 'أطفال',        campaigns: 6,  conversions: 290 },
  ],
}