import type { MarketplaceData } from '../-marketplace.types'

export const mockMarketplaceData: MarketplaceData = {
  stats: {
    totalProducts: 12,
    avgCommission: 680,
    topCommission: 2400,
  },
  products: [
    {
      id: 'p1',
      name: 'سماعات بلوتوث XG500 Pro',
      merchantName: 'تيك ستور الجزائر',
      merchantId: 'm1',
      category: 'إلكترونيات',
      status: 'hot',
      thumbnail: '🎧',
      msrpPrice: 8500,
      basePrice: 6100,
      minSellingPrice: 7000,
      commission: 2400,
      commissionRate: 28,
      deliveredRate: 82,
      retourRate: 11,
      totalSales: 341,
      description:
        'سماعات لاسلكية بجودة صوت استثنائية، عزل ضوضاء نشط، بطارية 40 ساعة. مناسبة للعمل والرياضة.',
      copywriting:
        '🎧 سماعات XG500 Pro — الصوت اللي تستاهله!\n✅ عزل ضوضاء 100%\n✅ بطارية 40 ساعة\n✅ توصيل لكل ولايات الجزائر\n💰 ادفع عند الاستلام',
      variants: [
        { id: 'v1', label: 'أسود', stock: 47 },
        { id: 'v2', label: 'أبيض', stock: 23 },
        { id: 'v3', label: 'رمادي', stock: 12 },
      ],
      media: {
        images: ['🎧', '📦', '🔋'],
        driveUrl: 'https://drive.google.com/drive/folders/xg500pro',
        hasVideo: true,
      },
      tags: ['bestseller', 'cod'],
    },
    {
      id: 'p2',
      name: 'كريم مرطب فيتامين C نهاري',
      merchantName: 'بيوتي برو',
      merchantId: 'm3',
      category: 'تجميل',
      status: 'active',
      thumbnail: '🧴',
      msrpPrice: 2800,
      basePrice: 1900,
      minSellingPrice: 2300,
      commission: 900,
      commissionRate: 32,
      deliveredRate: 79,
      retourRate: 13,
      totalSales: 218,
      description:
        'كريم نهاري غني بفيتامين C وحمض الهيالورونيك. يوحّد لون البشرة ويمنحها إشراقاً طبيعياً.',
      copywriting:
        '✨ بشرتك تستحق الأفضل!\nكريم فيتامين C الأصلي 100%\n🌿 مكونات طبيعية\n💧 ترطيب عميق 24 ساعة\nجربيه وشوفي الفرق من أول استخدام ✅',
      variants: [
        { id: 'v1', label: '50ml', stock: 89 },
        { id: 'v2', label: '100ml', stock: 34 },
      ],
      media: {
        images: ['🧴', '🌿', '💆'],
        driveUrl: 'https://drive.google.com/drive/folders/vitaminc',
        hasVideo: true,
      },
      tags: ['women', 'skincare'],
    },
    {
      id: 'p3',
      name: 'حذاء رياضي Boost X3',
      merchantName: 'سبور لاند',
      merchantId: 'm4',
      category: 'رياضة',
      status: 'active',
      thumbnail: '👟',
      msrpPrice: 6200,
      basePrice: 4500,
      minSellingPrice: 5000,
      commission: 1700,
      commissionRate: 27,
      deliveredRate: 68,
      retourRate: 24,
      totalSales: 156,
      description: 'حذاء رياضي خفيف الوزن مع نعل مرن وتهوية ممتازة. مناسب للجري والتدريب اليومي.',
      copywriting:
        '👟 Boost X3 — خطوتك الأولى للبطولة\n🏃 خفيف كالريشة\n💪 نعل مقاوم للانزلاق\nمتوفر بكل المقاسات 🇩🇿',
      variants: [
        { id: 'v1', label: '40', stock: 8 },
        { id: 'v2', label: '41', stock: 15 },
        { id: 'v3', label: '42', stock: 22 },
        { id: 'v4', label: '43', stock: 19 },
        { id: 'v5', label: '44', stock: 6 },
      ],
      media: {
        images: ['👟', '📐', '🏃'],
        driveUrl: 'https://drive.google.com/drive/folders/boostx3',
        hasVideo: false,
      },
      tags: ['sport', 'men'],
    },
    {
      id: 'p4',
      name: 'لعبة تعليمية STEM روبوت',
      merchantName: 'كيدز ورلد',
      merchantId: 'm5',
      category: 'أطفال',
      status: 'limited',
      thumbnail: '🤖',
      msrpPrice: 4500,
      basePrice: 3200,
      minSellingPrice: 3800,
      commission: 1300,
      commissionRate: 29,
      deliveredRate: 71,
      retourRate: 21,
      totalSales: 94,
      description: 'روبوت تعليمي للأطفال من 6-12 سنة. يعلّم أساسيات البرمجة والتفكير المنطقي.',
      copywriting:
        '🤖 هدية ما أحلاها!\nروبوت STEM يعلّم طفلك البرمجة لعباً\n🎓 موصى به من المختصين\n🎁 يجي في علبة هدية أنيقة\n✅ ضمان سنة كاملة',
      variants: [
        { id: 'v1', label: 'أزرق', stock: 11 },
        { id: 'v2', label: 'أحمر', stock: 7 },
      ],
      media: {
        images: ['🤖', '🎓', '📦'],
        driveUrl: 'https://drive.google.com/drive/folders/stemrobot',
        hasVideo: true,
      },
      tags: ['kids', 'educational', 'gift'],
    },
    {
      id: 'p5',
      name: 'جاكيت جلد كلاسيكي رجالي',
      merchantName: 'موضة 24',
      merchantId: 'm2',
      category: 'ملابس',
      status: 'active',
      thumbnail: '🧥',
      msrpPrice: 12000,
      basePrice: 9000,
      minSellingPrice: 10000,
      commission: 3000,
      commissionRate: 25,
      deliveredRate: 76,
      retourRate: 16,
      totalSales: 87,
      description: 'جاكيت جلد طبيعي 100%، مبطّن، أنيق ودافئ. متوفر بمقاسات S حتى XXL.',
      copywriting:
        '🧥 الأناقة الحقيقية من جلد طبيعي\n💎 جودة فاخرة\n🌡️ دافئ للشتاء\n📏 كل المقاسات متوفرة\nوالتوصيل مجاني! 🚚',
      variants: [
        { id: 'v1', label: 'S', stock: 5 },
        { id: 'v2', label: 'M', stock: 14 },
        { id: 'v3', label: 'L', stock: 18 },
        { id: 'v4', label: 'XL', stock: 9 },
        { id: 'v5', label: 'XXL', stock: 4 },
      ],
      media: {
        images: ['🧥', '✨', '📦'],
        driveUrl: 'https://drive.google.com/drive/folders/leatherjacket',
        hasVideo: false,
      },
      tags: ['men', 'winter', 'premium'],
    },
    {
      id: 'p6',
      name: 'مكيف هواء نقال 12000 BTU',
      merchantName: 'تيك ستور الجزائر',
      merchantId: 'm1',
      category: 'منزل',
      status: 'hot',
      thumbnail: '❄️',
      msrpPrice: 38000,
      basePrice: 30000,
      minSellingPrice: 33000,
      commission: 8000,
      commissionRate: 21,
      deliveredRate: 74,
      retourRate: 9,
      totalSales: 62,
      description:
        'مكيف نقال بقدرة 12000 BTU، تبريد سريع، موفّر للطاقة، مناسب لغرف حتى 30م².',
      copywriting:
        '❄️ الصيف مجاش بعد ما عندك هذا المكيف!\n⚡ تبريد في دقائق\n💡 يوفر 40% من الكهرباء\n🏠 يمشي معك من غرفة لغرفة\nتوصيل لكل الجزائر 🇩🇿',
      variants: [{ id: 'v1', label: 'أبيض / 12000 BTU', stock: 31 }],
      media: {
        images: ['❄️', '🏠', '⚡'],
        driveUrl: 'https://drive.google.com/drive/folders/ac12000',
        hasVideo: true,
      },
      tags: ['summer', 'home', 'highvalue'],
    },
    {
      id: 'p7',
      name: 'مكمل غذائي Omega-3 Triple',
      merchantName: 'بيوتي برو',
      merchantId: 'm3',
      category: 'صحة',
      status: 'active',
      thumbnail: '💊',
      msrpPrice: 1800,
      basePrice: 1100,
      minSellingPrice: 1400,
      commission: 700,
      commissionRate: 39,
      deliveredRate: 81,
      retourRate: 8,
      totalSales: 412,
      description:
        'أوميغا-3 تركيز ثلاثي من زيت السمك النقي. يدعم صحة القلب والمفاصل والذاكرة.',
      copywriting:
        '💊 صحتك أهم استثمار!\nOmega-3 Triple — تركيز 3 أضعاف العادي\n❤️ للقلب والمفاصل والتركيز\n✅ معتمد دولياً\n90 كبسولة تكفي 3 شهور',
      variants: [{ id: 'v1', label: '90 كبسولة', stock: 200 }],
      media: {
        images: ['💊', '❤️', '🧬'],
        driveUrl: 'https://drive.google.com/drive/folders/omega3',
        hasVideo: false,
      },
      tags: ['health', 'supplements', 'recurring'],
    },
    {
      id: 'p8',
      name: 'ساعة ذكية ProWatch S8',
      merchantName: 'تيك ستور الجزائر',
      merchantId: 'm1',
      category: 'إلكترونيات',
      status: 'active',
      thumbnail: '⌚',
      msrpPrice: 9500,
      basePrice: 7200,
      minSellingPrice: 8000,
      commission: 2300,
      commissionRate: 24,
      deliveredRate: 77,
      retourRate: 14,
      totalSales: 198,
      description: 'ساعة ذكية مع شاشة AMOLED، متابعة اللياقة، GPS، وبطارية 7 أيام.',
      copywriting:
        '⌚ ProWatch S8 — أكثر من مجرد ساعة\n📍 GPS دقيق\n❤️ يراقب معدل القلب 24/7\n🔋 بطارية أسبوع كامل\nهدية مثالية 🎁',
      variants: [
        { id: 'v1', label: 'أسود', stock: 28 },
        { id: 'v2', label: 'فضي', stock: 19 },
        { id: 'v3', label: 'ذهبي وردي', stock: 11 },
      ],
      media: {
        images: ['⌚', '📱', '🏃'],
        driveUrl: 'https://drive.google.com/drive/folders/prowatch',
        hasVideo: true,
      },
      tags: ['tech', 'gift', 'unisex'],
    },
  ],
}