import type { AffiliatesData } from '../affiliates.types'

export const affiliatesMock: AffiliatesData = {
  totalAffiliates: 10,
  activeAffiliates: 7,
  totalCommissionsPaid: 3_850_000,
  affiliates: [
    {
      id: 'aff-001',
      name: 'Youcef Benali',
      email: 'youcef@gmail.com',
      wilaya: 'Alger',
      status: 'active',
      conversions: 278,
      totalSales: 2_800_000,
      commissionRate: 8,
      joinedAt: '2024-01-15',
    },
    {
      id: 'aff-002',
      name: 'Meriem Hadj',
      email: 'meriem@gmail.com',
      wilaya: 'Oran',
      status: 'active',
      conversions: 241,
      totalSales: 2_100_000,
      commissionRate: 8,
      joinedAt: '2024-02-20',
    },
    {
      id: 'aff-003',
      name: 'Karim Zouaoui',
      email: 'karim@gmail.com',
      wilaya: 'Constantine',
      status: 'active',
      conversions: 198,
      totalSales: 1_800_000,
      commissionRate: 7,
      joinedAt: '2024-03-10',
    },
    {
      id: 'aff-004',
      name: 'Nassima Khelif',
      email: 'nassima@gmail.com',
      wilaya: 'Sétif',
      status: 'active',
      conversions: 176,
      totalSales: 1_500_000,
      commissionRate: 7,
      joinedAt: '2024-03-25',
    },
    {
      id: 'aff-005',
      name: 'Hamid Boukhalfa',
      email: 'hamid@gmail.com',
      wilaya: 'Annaba',
      status: 'active',
      conversions: 154,
      totalSales: 1_200_000,
      commissionRate: 6,
      joinedAt: '2024-04-05',
    },
    {
      id: 'aff-006',
      name: 'Sofiane Merad',
      email: 'sofiane@gmail.com',
      wilaya: 'Sétif',
      status: 'pending',
      conversions: 45,
      totalSales: 380_000,
      commissionRate: 5,
      joinedAt: '2024-11-01',
    },
    {
      id: 'aff-007',
      name: 'Rania Boudaoud',
      email: 'rania@gmail.com',
      wilaya: 'Blida',
      status: 'active',
      conversions: 132,
      totalSales: 990_000,
      commissionRate: 6,
      joinedAt: '2024-05-18',
    },
    {
      id: 'aff-008',
      name: 'Bilal Amrani',
      email: 'bilal@gmail.com',
      wilaya: 'Tizi Ouzou',
      status: 'suspended',
      conversions: 89,
      totalSales: 620_000,
      commissionRate: 5,
      joinedAt: '2024-06-30',
    },
    {
      id: 'aff-009',
      name: 'Chaima Ferhat',
      email: 'chaima@gmail.com',
      wilaya: 'Béjaïa',
      status: 'suspended',
      conversions: 67,
      totalSales: 450_000,
      commissionRate: 5,
      joinedAt: '2024-07-12',
    },
    {
      id: 'aff-010',
      name: 'Omar Tlemcani',
      email: 'omar@gmail.com',
      wilaya: 'Tlemcen',
      status: 'pending',
      conversions: 12,
      totalSales: 95_000,
      commissionRate: 5,
      joinedAt: '2024-12-01',
    },
  ],
}
