// merchant/orders/-server/orders.mock.ts

import type { MerchantOrdersData } from '../orders.types'

export const mockMerchantOrders: MerchantOrdersData = {
  tabCounts: {
    all: 47,
    pending: 12,
    shipped: 18,
    delivered: 11,
    returned: 6,
  },

  orders: [
    {
      id: 'ORD-0042',
      createdAt: '2025-07-07',
      product: { name: 'حذاء رياضي أبيض', variant: 'مقاس 42' },
      customer: { name: 'كريم بن علي',  phone: '0550 123 456' },
      wilaya: 'الجزائر',
      totalPrice: 3200,
      merchantEarnings: 2400,
      status: 'pending',
    },
    {
      id: 'ORD-0041',
      createdAt: '2025-07-06',
      product: { name: 'سترة شتوية', variant: 'L — كحلي' },
      customer: { name: 'سارة مزياني', phone: '0661 789 012' },
      wilaya: 'وهران',
      totalPrice: 5500,
      merchantEarnings: 4000,
      status: 'shipped',
      trackingNumber: 'YAL-2025-88741',
    },
    {
      id: 'ORD-0040',
      createdAt: '2025-07-05',
      product: { name: 'حقيبة جلدية بنية', variant: 'قياس وسط' },
      customer: { name: 'يوسف حداد',  phone: '0770 345 678' },
      wilaya: 'سطيف',
      totalPrice: 4800,
      merchantEarnings: 3500,
      status: 'delivered',
    },
    {
      id: 'ORD-0039',
      createdAt: '2025-07-04',
      product: { name: 'حذاء رياضي أبيض', variant: 'مقاس 40' },
      customer: { name: 'نادية قاسم',  phone: '0554 901 234' },
      wilaya: 'قسنطينة',
      totalPrice: 3200,
      merchantEarnings: 2400,
      status: 'returned',
    },
    {
      id: 'ORD-0038',
      createdAt: '2025-07-04',
      product: { name: 'حذاء رياضي أبيض', variant: 'مقاس 41' },
      customer: { name: 'أمين بلعيد',  phone: '0561 456 789' },
      wilaya: 'عنابة',
      totalPrice: 3200,
      merchantEarnings: 2400,
      status: 'pending',
    },
    {
      id: 'ORD-0037',
      createdAt: '2025-07-03',
      product: { name: 'سترة شتوية', variant: 'XL — رمادي' },
      customer: { name: 'إيمان زروق', phone: '0770 654 321' },
      wilaya: 'بجاية',
      totalPrice: 5500,
      merchantEarnings: 4000,
      status: 'shipped',
      trackingNumber: 'YAL-2025-88502',
    },
    {
      id: 'ORD-0036',
      createdAt: '2025-07-02',
      product: { name: 'حقيبة جلدية بنية', variant: 'قياس كبير' },
      customer: { name: 'طارق منصور', phone: '0550 111 222' },
      wilaya: 'تيزي وزو',
      totalPrice: 5200,
      merchantEarnings: 3800,
      status: 'delivered',
    },
  ],
}