// src/routes/merchant/affiliates/-server/affiliates.mock.ts

import type { AffiliatesPageData } from '../affiliates.types'

export const mockAffiliatesData: AffiliatesPageData = {
  stats: {
    activeAffiliates: 45,
    ordersThisMonth: 312,
    totalCommissions: 184500,
    conversionRate: 6.8,
  },
  affiliates: [
    {
      id: 'aff-001',
      name: 'يوسف حمداني',
      initials: 'يح',
      avatarColor: '#ddd1fe',
      phone: '0661 234 567',
      wilaya: 'الجزائر العاصمة',
      joinedAt: '2025-01-15',
      tier: 'gold',
      totalOrders: 142,
      deliveredOrders: 128,
      returnRate: 9.8,
      totalSales: 456800,
      totalCommissions: 34200,
      status: 'active',
      topProducts: [
        { productId: 'p-001', productName: 'حذاء رياضي أبيض', unitsSold: 47, commission: 11200 },
        { productId: 'p-002', productName: 'سترة شتوية كحلي', unitsSold: 38, commission: 9500 },
        { productId: 'p-003', productName: 'حقيبة جلدية بنية', unitsSold: 21, commission: 5250 },
      ],
      last30DaysSales: [
        { day: 1, orders: 2 }, { day: 3, orders: 4 }, { day: 6, orders: 3 },
        { day: 9, orders: 6 }, { day: 12, orders: 8 }, { day: 15, orders: 7 },
        { day: 18, orders: 9 }, { day: 21, orders: 11 }, { day: 24, orders: 10 },
        { day: 27, orders: 12 }, { day: 30, orders: 9 },
      ],
    },
    {
      id: 'aff-002',
      name: 'سارة بوعلام',
      initials: 'سب',
      avatarColor: '#d1fae5',
      phone: '0770 456 789',
      wilaya: 'وهران',
      joinedAt: '2025-03-10',
      tier: 'silver',
      totalOrders: 87,
      deliveredOrders: 74,
      returnRate: 14.9,
      totalSales: 287500,
      totalCommissions: 21600,
      status: 'active',
      topProducts: [
        { productId: 'p-001', productName: 'حذاء رياضي أبيض', unitsSold: 31, commission: 7400 },
        { productId: 'p-004', productName: 'حذاء كلاسيكي أسود', unitsSold: 24, commission: 5760 },
        { productId: 'p-002', productName: 'سترة شتوية كحلي', unitsSold: 12, commission: 3000 },
      ],
      last30DaysSales: [
        { day: 1, orders: 1 }, { day: 4, orders: 3 }, { day: 7, orders: 4 },
        { day: 10, orders: 5 }, { day: 13, orders: 6 }, { day: 16, orders: 5 },
        { day: 19, orders: 7 }, { day: 22, orders: 6 }, { day: 25, orders: 8 },
        { day: 28, orders: 7 }, { day: 30, orders: 5 },
      ],
    },
    {
      id: 'aff-003',
      name: 'كريم مصطفاوي',
      initials: 'كم',
      avatarColor: '#fee2e2',
      phone: '0554 321 098',
      wilaya: 'قسنطينة',
      joinedAt: '2025-02-20',
      tier: 'silver',
      totalOrders: 63,
      deliveredOrders: 45,
      returnRate: 28.5,
      totalSales: 198000,
      totalCommissions: 14800,
      status: 'active',
      topProducts: [
        { productId: 'p-003', productName: 'حقيبة جلدية بنية', unitsSold: 22, commission: 5500 },
        { productId: 'p-002', productName: 'سترة شتوية كحلي', unitsSold: 15, commission: 3750 },
        { productId: 'p-001', productName: 'حذاء رياضي أبيض', unitsSold: 8, commission: 1920 },
      ],
      last30DaysSales: [
        { day: 2, orders: 3 }, { day: 5, orders: 2 }, { day: 8, orders: 4 },
        { day: 11, orders: 3 }, { day: 14, orders: 5 }, { day: 17, orders: 4 },
        { day: 20, orders: 3 }, { day: 23, orders: 5 }, { day: 26, orders: 4 },
        { day: 29, orders: 3 }, { day: 30, orders: 2 },
      ],
    },
    {
      id: 'aff-004',
      name: 'نور تاوتي',
      initials: 'نت',
      avatarColor: '#fef3c7',
      phone: '0660 987 654',
      wilaya: 'عنابة',
      joinedAt: '2025-04-05',
      tier: 'bronze',
      totalOrders: 31,
      deliveredOrders: 28,
      returnRate: 9.6,
      totalSales: 94500,
      totalCommissions: 7100,
      status: 'active',
      topProducts: [
        { productId: 'p-004', productName: 'حذاء كلاسيكي أسود', unitsSold: 14, commission: 3360 },
        { productId: 'p-001', productName: 'حذاء رياضي أبيض', unitsSold: 9, commission: 2160 },
        { productId: 'p-003', productName: 'حقيبة جلدية بنية', unitsSold: 5, commission: 1250 },
      ],
      last30DaysSales: [
        { day: 3, orders: 1 }, { day: 7, orders: 2 }, { day: 11, orders: 2 },
        { day: 15, orders: 3 }, { day: 18, orders: 2 }, { day: 21, orders: 3 },
        { day: 24, orders: 4 }, { day: 27, orders: 3 }, { day: 30, orders: 2 },
      ],
    },
    {
      id: 'aff-005',
      name: 'عمار بلعيد',
      initials: 'عب',
      avatarColor: '#f1f5f9',
      phone: '0771 654 321',
      wilaya: 'سطيف',
      joinedAt: '2025-01-28',
      tier: 'bronze',
      totalOrders: 19,
      deliveredOrders: 14,
      returnRate: 26.3,
      totalSales: 57200,
      totalCommissions: 4200,
      status: 'blocked',
      topProducts: [
        { productId: 'p-002', productName: 'سترة شتوية كحلي', unitsSold: 8, commission: 2000 },
        { productId: 'p-003', productName: 'حقيبة جلدية بنية', unitsSold: 4, commission: 1000 },
        { productId: 'p-001', productName: 'حذاء رياضي أبيض', unitsSold: 2, commission: 480 },
      ],
      last30DaysSales: [],
    },
  ],
}