// src/routes/_dashboard/merchants/-server/merchants.mock.ts
import type { Merchant,  } from '../-merchants.types'
import type { JoinRequest } from '../../-shared/-shared.types'

export const MOCK_MERCHANTS: Merchant[] = [
  {
    id: 'm1',
    name: 'كريم بن علي',
    email: 'karim@techstore.dz',
    phone: '0551 234 567',
    wilaya: 'الجزائر العاصمة',
    businessName: 'TechStore DZ',
    status: 'active',
    joinedAt: '2025-11-03',
    totalProducts: 24,
    totalOrders: 312,
    totalRevenue: 1_840_000,
    commissionRate: 5,
    warnings: [],
    products: [
      { id: 'p1', name: 'سماعات بلوتوث Pro', price: 8500, stock: 45, category: 'إلكترونيات', status: 'active' },
      { id: 'p2', name: 'شاحن لاسلكي 65W', price: 3200, stock: 120, category: 'إلكترونيات', status: 'active' },
      { id: 'p3', name: 'حافظة هاتف مقاومة للماء', price: 1800, stock: 0, category: 'إكسسوارات', status: 'inactive' },
    ],
  },
  {
    id: 'm2',
    name: 'سارة مزياني',
    email: 'sara@modadz.dz',
    phone: '0661 987 432',
    wilaya: 'وهران',
    businessName: 'Moda DZ',
    status: 'active',
    joinedAt: '2025-12-18',
    totalProducts: 58,
    totalOrders: 875,
    totalRevenue: 3_210_000,
    commissionRate: 7,
    warnings: [
      { id: 'w1', message: 'تأخر في تأكيد الطلبات لأكثر من 48 ساعة', sentAt: '2026-03-10' },
    ],
    products: [
      { id: 'p5', name: 'عباية كلاسيكية فاخرة', price: 12000, stock: 30, category: 'أزياء', status: 'active' },
      { id: 'p6', name: 'حقيبة يد جلد طبيعي', price: 18500, stock: 15, category: 'أزياء', status: 'active' },
    ],
  },
  {
    id: 'm3',
    name: 'يوسف بوعزيز',
    email: 'youcef@fitnesszone.dz',
    phone: '0770 345 891',
    wilaya: 'قسنطينة',
    businessName: 'FitnessZone',
    status: 'suspended',
    joinedAt: '2026-01-05',
    totalProducts: 17,
    totalOrders: 143,
    totalRevenue: 620_000,
    commissionRate: 5,
    warnings: [
      { id: 'w2', message: 'منتجات غير مطابقة للمواصفات المعلنة', sentAt: '2026-02-14' },
      { id: 'w3', message: 'تكرار شكاوى العملاء — إجراء تحقيق', sentAt: '2026-04-01' },
    ],
    products: [
      { id: 'p8', name: 'حبل القفز الاحترافي', price: 2100, stock: 80, category: 'رياضة', status: 'active' },
    ],
  },
  {
    id: 'm4',
    name: 'أمينة حداد',
    email: 'amina@beautydz.dz',
    phone: '0555 678 123',
    wilaya: 'سطيف',
    businessName: 'Beauty Corner DZ',
    status: 'pending',
    joinedAt: '2026-04-28',
    totalProducts: 0,
    totalOrders: 0,
    totalRevenue: 0,
    commissionRate: 6,
    warnings: [],
    products: [],
  },
  {
    id: 'm5',
    name: 'رضا بلعيد',
    email: 'rida@homestyle.dz',
    phone: '0662 112 789',
    wilaya: 'عنابة',
    businessName: 'HomeStyle DZ',
    status: 'active',
    joinedAt: '2025-10-20',
    totalProducts: 41,
    totalOrders: 528,
    totalRevenue: 2_450_000,
    commissionRate: 5,
    warnings: [],
    products: [
      { id: 'p10', name: 'طقم أواني تيفال 8 قطع', price: 15000, stock: 22, category: 'مطبخ', status: 'active' },
      { id: 'p11', name: 'مكيف هواء محمول', price: 45000, stock: 8, category: 'أجهزة منزلية', status: 'active' },
    ],
  },
]

export const MOCK_JOIN_REQUESTS: JoinRequest[] = [
  {
    id: 'r1',
    name: 'نور الدين بلحاج',
    email: 'nour@greenmarket.dz',
    phone: '0550 112 334',
    wilaya: 'بجاية',
    businessName: 'Green Market DZ',
    category: 'غذاء وتغذية',
    requestedAt: '2026-05-10',
    description: 'متجر متخصص في المنتجات العضوية والطبيعية المحلية.',
    registrationNumber: 'RC-2026-BJ-4412',
    status: 'pending',
  },
  {
    id: 'r2',
    name: 'لمياء قاسمي',
    email: 'lamia@artisandz.dz',
    phone: '0771 556 788',
    wilaya: 'تيزي وزو',
    businessName: 'Artisan DZ',
    category: 'حرف يدوية',
    requestedAt: '2026-05-12',
    description: 'بيع الصناعات اليدوية الأمازيغية الأصيلة والمطرزات التقليدية.',
    registrationNumber: 'RC-2026-TZ-8821',
    status: 'pending',
  },
  {
    id: 'r3',
    name: 'عمر بن حميدة',
    email: 'omar@techparts.dz',
    phone: '0662 449 001',
    wilaya: 'ورقلة',
    businessName: 'TechParts DZ',
    category: 'إلكترونيات',
    requestedAt: '2026-05-14',
    description: 'توريد وبيع قطع غيار الكمبيوتر والأجهزة الإلكترونية.',
    registrationNumber: 'RC-2026-OR-1193',
    status: 'pending',
  },
]