/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as MerchantWalletIndexRouteImport } from './routes/merchant/wallet/index'
import { Route as MerchantSettingsIndexRouteImport } from './routes/merchant/settings/index'
import { Route as MerchantProductsIndexRouteImport } from './routes/merchant/products/index'
import { Route as MerchantOrdersIndexRouteImport } from './routes/merchant/orders/index'
import { Route as MerchantDashboardIndexRouteImport } from './routes/merchant/dashboard/index'
import { Route as MerchantAffiliatesIndexRouteImport } from './routes/merchant/affiliates/index'
import { Route as AffiliateWalletIndexRouteImport } from './routes/affiliate/wallet/index'
import { Route as AffiliateSettingsIndexRouteImport } from './routes/affiliate/settings/index'
import { Route as AffiliateOrdersIndexRouteImport } from './routes/affiliate/orders/index'
import { Route as AffiliateMarketplaceIndexRouteImport } from './routes/affiliate/marketplace/index'
import { Route as AffiliateDashboardIndexRouteImport } from './routes/affiliate/dashboard/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/_dashboard/settings/index'
import { Route as DashboardProductsIndexRouteImport } from './routes/_dashboard/products/index'
import { Route as DashboardOrdersIndexRouteImport } from './routes/_dashboard/orders/index'
import { Route as DashboardMerchantsIndexRouteImport } from './routes/_dashboard/merchants/index'
import { Route as DashboardIntegrationIndexRouteImport } from './routes/_dashboard/integration/index'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as DashboardCommissionsIndexRouteImport } from './routes/_dashboard/commissions/index'
import { Route as DashboardAnalyticsIndexRouteImport } from './routes/_dashboard/analytics/index'
import { Route as DashboardAffiliatesIndexRouteImport } from './routes/_dashboard/affiliates/index'
import { Route as ApiWebhooksEcotrackRouteImport } from './routes/api/webhooks/ecotrack'
import { Route as ApiCronReleaseFundsRouteImport } from './routes/api/cron/release-funds'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const MerchantWalletIndexRoute = MerchantWalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantSettingsIndexRoute = MerchantSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantProductsIndexRoute = MerchantProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantOrdersIndexRoute = MerchantOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantDashboardIndexRoute = MerchantDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantAffiliatesIndexRoute = MerchantAffiliatesIndexRouteImport.update({
  id: '/affiliates/',
  path: '/affiliates/',
  getParentRoute: () => MerchantRoute,
} as any)
const AffiliateWalletIndexRoute = AffiliateWalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => AffiliateRoute,
} as any)
const AffiliateSettingsIndexRoute = AffiliateSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AffiliateRoute,
} as any)
const AffiliateOrdersIndexRoute = AffiliateOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AffiliateRoute,
} as any)
const AffiliateMarketplaceIndexRoute =
  AffiliateMarketplaceIndexRouteImport.update({
    id: '/marketplace/',
    path: '/marketplace/',
    getParentRoute: () => AffiliateRoute,
  } as any)
const AffiliateDashboardIndexRoute = AffiliateDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AffiliateRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMerchantsIndexRoute = DashboardMerchantsIndexRouteImport.update({
  id: '/merchants/',
  path: '/merchants/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntegrationIndexRoute =
  DashboardIntegrationIndexRouteImport.update({
    id: '/integration/',
    path: '/integration/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommissionsIndexRoute =
  DashboardCommissionsIndexRouteImport.update({
    id: '/commissions/',
    path: '/commissions/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAnalyticsIndexRoute = DashboardAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAffiliatesIndexRoute =
  DashboardAffiliatesIndexRouteImport.update({
    id: '/affiliates/',
    path: '/affiliates/',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiWebhooksEcotrackRoute = ApiWebhooksEcotrackRouteImport.update({
  id: '/api/webhooks/ecotrack',
  path: '/api/webhooks/ecotrack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronReleaseFundsRoute = ApiCronReleaseFundsRouteImport.update({
  id: '/api/cron/release-funds',
  path: '/api/cron/release-funds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRouteWithChildren
  '/merchant': typeof MerchantRouteWithChildren
  '/pending-approval': typeof PendingApprovalRoute
  '/set-password': typeof SetPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/release-funds': typeof ApiCronReleaseFundsRoute
  '/api/webhooks/ecotrack': typeof ApiWebhooksEcotrackRoute
  '/affiliates/': typeof DashboardAffiliatesIndexRoute
  '/analytics/': typeof DashboardAnalyticsIndexRoute
  '/commissions/': typeof DashboardCommissionsIndexRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
  '/integration/': typeof DashboardIntegrationIndexRoute
  '/merchants/': typeof DashboardMerchantsIndexRoute
  '/orders/': typeof DashboardOrdersIndexRoute
  '/products/': typeof DashboardProductsIndexRoute
  '/settings/': typeof DashboardSettingsIndexRoute
  '/affiliate/dashboard/': typeof AffiliateDashboardIndexRoute
  '/affiliate/marketplace/': typeof AffiliateMarketplaceIndexRoute
  '/affiliate/orders/': typeof AffiliateOrdersIndexRoute
  '/affiliate/settings/': typeof AffiliateSettingsIndexRoute
  '/affiliate/wallet/': typeof AffiliateWalletIndexRoute
  '/merchant/affiliates/': typeof MerchantAffiliatesIndexRoute
  '/merchant/dashboard/': typeof MerchantDashboardIndexRoute
  '/merchant/orders/': typeof MerchantOrdersIndexRoute
  '/merchant/products/': typeof MerchantProductsIndexRoute
  '/merchant/settings/': typeof MerchantSettingsIndexRoute
  '/merchant/wallet/': typeof MerchantWalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRouteWithChildren
  '/merchant': typeof MerchantRouteWithChildren
  '/pending-approval': typeof PendingApprovalRoute
  '/set-password': typeof SetPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/release-funds': typeof ApiCronReleaseFundsRoute
  '/api/webhooks/ecotrack': typeof ApiWebhooksEcotrackRoute
  '/affiliates': typeof DashboardAffiliatesIndexRoute
  '/analytics': typeof DashboardAnalyticsIndexRoute
  '/commissions': typeof DashboardCommissionsIndexRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/integration': typeof DashboardIntegrationIndexRoute
  '/merchants': typeof DashboardMerchantsIndexRoute
  '/orders': typeof DashboardOrdersIndexRoute
  '/products': typeof DashboardProductsIndexRoute
  '/settings': typeof DashboardSettingsIndexRoute
  '/affiliate/dashboard': typeof AffiliateDashboardIndexRoute
  '/affiliate/marketplace': typeof AffiliateMarketplaceIndexRoute
  '/affiliate/orders': typeof AffiliateOrdersIndexRoute
  '/affiliate/settings': typeof AffiliateSettingsIndexRoute
  '/affiliate/wallet': typeof AffiliateWalletIndexRoute
  '/merchant/affiliates': typeof MerchantAffiliatesIndexRoute
  '/merchant/dashboard': typeof MerchantDashboardIndexRoute
  '/merchant/orders': typeof MerchantOrdersIndexRoute
  '/merchant/products': typeof MerchantProductsIndexRoute
  '/merchant/settings': typeof MerchantSettingsIndexRoute
  '/merchant/wallet': typeof MerchantWalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRouteWithChildren
  '/merchant': typeof MerchantRouteWithChildren
  '/pending-approval': typeof PendingApprovalRoute
  '/set-password': typeof SetPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/release-funds': typeof ApiCronReleaseFundsRoute
  '/api/webhooks/ecotrack': typeof ApiWebhooksEcotrackRoute
  '/_dashboard/affiliates/': typeof DashboardAffiliatesIndexRoute
  '/_dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/_dashboard/commissions/': typeof DashboardCommissionsIndexRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/integration/': typeof DashboardIntegrationIndexRoute
  '/_dashboard/merchants/': typeof DashboardMerchantsIndexRoute
  '/_dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/_dashboard/products/': typeof DashboardProductsIndexRoute
  '/_dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/affiliate/dashboard/': typeof AffiliateDashboardIndexRoute
  '/affiliate/marketplace/': typeof AffiliateMarketplaceIndexRoute
  '/affiliate/orders/': typeof AffiliateOrdersIndexRoute
  '/affiliate/settings/': typeof AffiliateSettingsIndexRoute
  '/affiliate/wallet/': typeof AffiliateWalletIndexRoute
  '/merchant/affiliates/': typeof MerchantAffiliatesIndexRoute
  '/merchant/dashboard/': typeof MerchantDashboardIndexRoute
  '/merchant/orders/': typeof MerchantOrdersIndexRoute
  '/merchant/products/': typeof MerchantProductsIndexRoute
  '/merchant/settings/': typeof MerchantSettingsIndexRoute
  '/merchant/wallet/': typeof MerchantWalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliate'
    | '/merchant'
    | '/pending-approval'
    | '/set-password'
    | '/login'
    | '/register'
    | '/api/auth/$'
    | '/api/cron/release-funds'
    | '/api/webhooks/ecotrack'
    | '/affiliates/'
    | '/analytics/'
    | '/commissions/'
    | '/dashboard/'
    | '/integration/'
    | '/merchants/'
    | '/orders/'
    | '/products/'
    | '/settings/'
    | '/affiliate/dashboard/'
    | '/affiliate/marketplace/'
    | '/affiliate/orders/'
    | '/affiliate/settings/'
    | '/affiliate/wallet/'
    | '/merchant/affiliates/'
    | '/merchant/dashboard/'
    | '/merchant/orders/'
    | '/merchant/products/'
    | '/merchant/settings/'
    | '/merchant/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliate'
    | '/merchant'
    | '/pending-approval'
    | '/set-password'
    | '/login'
    | '/register'
    | '/api/auth/$'
    | '/api/cron/release-funds'
    | '/api/webhooks/ecotrack'
    | '/affiliates'
    | '/analytics'
    | '/commissions'
    | '/dashboard'
    | '/integration'
    | '/merchants'
    | '/orders'
    | '/products'
    | '/settings'
    | '/affiliate/dashboard'
    | '/affiliate/marketplace'
    | '/affiliate/orders'
    | '/affiliate/settings'
    | '/affiliate/wallet'
    | '/merchant/affiliates'
    | '/merchant/dashboard'
    | '/merchant/orders'
    | '/merchant/products'
    | '/merchant/settings'
    | '/merchant/wallet'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/about'
    | '/affiliate'
    | '/merchant'
    | '/pending-approval'
    | '/set-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/api/auth/$'
    | '/api/cron/release-funds'
    | '/api/webhooks/ecotrack'
    | '/_dashboard/affiliates/'
    | '/_dashboard/analytics/'
    | '/_dashboard/commissions/'
    | '/_dashboard/dashboard/'
    | '/_dashboard/integration/'
    | '/_dashboard/merchants/'
    | '/_dashboard/orders/'
    | '/_dashboard/products/'
    | '/_dashboard/settings/'
    | '/affiliate/dashboard/'
    | '/affiliate/marketplace/'
    | '/affiliate/orders/'
    | '/affiliate/settings/'
    | '/affiliate/wallet/'
    | '/merchant/affiliates/'
    | '/merchant/dashboard/'
    | '/merchant/orders/'
    | '/merchant/products/'
    | '/merchant/settings/'
    | '/merchant/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  AboutRoute: typeof AboutRoute
  AffiliateRoute: typeof AffiliateRouteWithChildren
  MerchantRoute: typeof MerchantRouteWithChildren
  PendingApprovalRoute: typeof PendingApprovalRoute
  SetPasswordRoute: typeof SetPasswordRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronReleaseFundsRoute: typeof ApiCronReleaseFundsRoute
  ApiWebhooksEcotrackRoute: typeof ApiWebhooksEcotrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/merchant/wallet/': {
      id: '/merchant/wallet/'
      path: '/wallet'
      fullPath: '/merchant/wallet/'
      preLoaderRoute: typeof MerchantWalletIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/settings/': {
      id: '/merchant/settings/'
      path: '/settings'
      fullPath: '/merchant/settings/'
      preLoaderRoute: typeof MerchantSettingsIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/products/': {
      id: '/merchant/products/'
      path: '/products'
      fullPath: '/merchant/products/'
      preLoaderRoute: typeof MerchantProductsIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/orders/': {
      id: '/merchant/orders/'
      path: '/orders'
      fullPath: '/merchant/orders/'
      preLoaderRoute: typeof MerchantOrdersIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/dashboard/': {
      id: '/merchant/dashboard/'
      path: '/dashboard'
      fullPath: '/merchant/dashboard/'
      preLoaderRoute: typeof MerchantDashboardIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/affiliates/': {
      id: '/merchant/affiliates/'
      path: '/affiliates'
      fullPath: '/merchant/affiliates/'
      preLoaderRoute: typeof MerchantAffiliatesIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/affiliate/wallet/': {
      id: '/affiliate/wallet/'
      path: '/wallet'
      fullPath: '/affiliate/wallet/'
      preLoaderRoute: typeof AffiliateWalletIndexRouteImport
      parentRoute: typeof AffiliateRoute
    }
    '/affiliate/settings/': {
      id: '/affiliate/settings/'
      path: '/settings'
      fullPath: '/affiliate/settings/'
      preLoaderRoute: typeof AffiliateSettingsIndexRouteImport
      parentRoute: typeof AffiliateRoute
    }
    '/affiliate/orders/': {
      id: '/affiliate/orders/'
      path: '/orders'
      fullPath: '/affiliate/orders/'
      preLoaderRoute: typeof AffiliateOrdersIndexRouteImport
      parentRoute: typeof AffiliateRoute
    }
    '/affiliate/marketplace/': {
      id: '/affiliate/marketplace/'
      path: '/marketplace'
      fullPath: '/affiliate/marketplace/'
      preLoaderRoute: typeof AffiliateMarketplaceIndexRouteImport
      parentRoute: typeof AffiliateRoute
    }
    '/affiliate/dashboard/': {
      id: '/affiliate/dashboard/'
      path: '/dashboard'
      fullPath: '/affiliate/dashboard/'
      preLoaderRoute: typeof AffiliateDashboardIndexRouteImport
      parentRoute: typeof AffiliateRoute
    }
    '/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/products/': {
      id: '/_dashboard/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/orders/': {
      id: '/_dashboard/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/merchants/': {
      id: '/_dashboard/merchants/'
      path: '/merchants'
      fullPath: '/merchants/'
      preLoaderRoute: typeof DashboardMerchantsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/integration/': {
      id: '/_dashboard/integration/'
      path: '/integration'
      fullPath: '/integration/'
      preLoaderRoute: typeof DashboardIntegrationIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/commissions/': {
      id: '/_dashboard/commissions/'
      path: '/commissions'
      fullPath: '/commissions/'
      preLoaderRoute: typeof DashboardCommissionsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/analytics/': {
      id: '/_dashboard/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof DashboardAnalyticsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/affiliates/': {
      id: '/_dashboard/affiliates/'
      path: '/affiliates'
      fullPath: '/affiliates/'
      preLoaderRoute: typeof DashboardAffiliatesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/webhooks/ecotrack': {
      id: '/api/webhooks/ecotrack'
      path: '/api/webhooks/ecotrack'
      fullPath: '/api/webhooks/ecotrack'
      preLoaderRoute: typeof ApiWebhooksEcotrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/release-funds': {
      id: '/api/cron/release-funds'
      path: '/api/cron/release-funds'
      fullPath: '/api/cron/release-funds'
      preLoaderRoute: typeof ApiCronReleaseFundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardAffiliatesIndexRoute: typeof DashboardAffiliatesIndexRoute
  DashboardAnalyticsIndexRoute: typeof DashboardAnalyticsIndexRoute
  DashboardCommissionsIndexRoute: typeof DashboardCommissionsIndexRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardIntegrationIndexRoute: typeof DashboardIntegrationIndexRoute
  DashboardMerchantsIndexRoute: typeof DashboardMerchantsIndexRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAffiliatesIndexRoute: DashboardAffiliatesIndexRoute,
  DashboardAnalyticsIndexRoute: DashboardAnalyticsIndexRoute,
  DashboardCommissionsIndexRoute: DashboardCommissionsIndexRoute,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
  DashboardIntegrationIndexRoute: DashboardIntegrationIndexRoute,
  DashboardMerchantsIndexRoute: DashboardMerchantsIndexRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface AffiliateRouteChildren {
  AffiliateDashboardIndexRoute: typeof AffiliateDashboardIndexRoute
  AffiliateMarketplaceIndexRoute: typeof AffiliateMarketplaceIndexRoute
  AffiliateOrdersIndexRoute: typeof AffiliateOrdersIndexRoute
  AffiliateSettingsIndexRoute: typeof AffiliateSettingsIndexRoute
  AffiliateWalletIndexRoute: typeof AffiliateWalletIndexRoute
}

const AffiliateRouteChildren: AffiliateRouteChildren = {
  AffiliateDashboardIndexRoute: AffiliateDashboardIndexRoute,
  AffiliateMarketplaceIndexRoute: AffiliateMarketplaceIndexRoute,
  AffiliateOrdersIndexRoute: AffiliateOrdersIndexRoute,
  AffiliateSettingsIndexRoute: AffiliateSettingsIndexRoute,
  AffiliateWalletIndexRoute: AffiliateWalletIndexRoute,
}

const AffiliateRouteWithChildren = AffiliateRoute._addFileChildren(
  AffiliateRouteChildren,
)

interface MerchantRouteChildren {
  MerchantAffiliatesIndexRoute: typeof MerchantAffiliatesIndexRoute
  MerchantDashboardIndexRoute: typeof MerchantDashboardIndexRoute
  MerchantOrdersIndexRoute: typeof MerchantOrdersIndexRoute
  MerchantProductsIndexRoute: typeof MerchantProductsIndexRoute
  MerchantSettingsIndexRoute: typeof MerchantSettingsIndexRoute
  MerchantWalletIndexRoute: typeof MerchantWalletIndexRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantAffiliatesIndexRoute: MerchantAffiliatesIndexRoute,
  MerchantDashboardIndexRoute: MerchantDashboardIndexRoute,
  MerchantOrdersIndexRoute: MerchantOrdersIndexRoute,
  MerchantProductsIndexRoute: MerchantProductsIndexRoute,
  MerchantSettingsIndexRoute: MerchantSettingsIndexRoute,
  MerchantWalletIndexRoute: MerchantWalletIndexRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  AboutRoute: AboutRoute,
  AffiliateRoute: AffiliateRouteWithChildren,
  MerchantRoute: MerchantRouteWithChildren,
  PendingApprovalRoute: PendingApprovalRoute,
  SetPasswordRoute: SetPasswordRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronReleaseFundsRoute: ApiCronReleaseFundsRoute,
  ApiWebhooksEcotrackRoute: ApiWebhooksEcotrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
