import type { ProductsData } from '../-campaigns.types'

export const mockProductsData: ProductsData = {
  stats: {
    total:           { value: 47, change: 14 },
    active:          { value: 40, change:  9 },
    suspended:       { value:  5, change: -2 },
    highReturnCount: { value:  2, change:  1 },
  },
  products: [
    {
      id:             'p1',
      name:           'مكمل غذائي X',
      category:       'صحة',
      merchantName:   'HealthStore',
      merchantWilaya: 'قسنطينة',
      priceDzd:       2500,
      stockQty:       34,
      isActive:       false,
      returnRate:     76,
      conversions:    91,
      createdAt:      '2025-01-15',
    },
    {
      id:             'p2',
      name:           'قلادة قلب ذهبية',
      category:       'مجوهرات',
      merchantName:   'Bijoux DZ',
      merchantWilaya: 'الجزائر',
      priceDzd:       4500,
      stockQty:       120,
      isActive:       true,
      returnRate:     12,
      conversions:    278,
      createdAt:      '2025-02-03',
    },
    {
      id:             'p3',
      name:           'كريم العناية بالبشرة',
      category:       'جمال',
      merchantName:   'Beauty Algeria',
      merchantWilaya: 'عنابة',
      priceDzd:       1800,
      stockQty:       3,
      isActive:       true,
      returnRate:     21,
      conversions:    341,
      createdAt:      '2025-01-28',
    },
    {
      id:             'p4',
      name:           'سماعات بلوتوث Pro',
      category:       'إلكترونيات',
      merchantName:   'TechShop DZ',
      merchantWilaya: 'سطيف',
      priceDzd:       8900,
      stockQty:       67,
      isActive:       true,
      returnRate:     8,
      conversions:    193,
      createdAt:      '2025-03-10',
    },
  ],
}